### PR TITLE
feat: implement semantic release

### PR DESCRIPTION
**Pull request by daks**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [X] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [X] `[docs]`     Documentation changes
- [X] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

Not sure.

### Describe the changes you're proposing

Implement semantic release and tests/CI

### Documentation checklist

- [X] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by daks** [comment]
Still some linters to fix. 
Tests:
* OK on Debian 10 and Ubuntu 1804
* Centos, Fedora, OpenSuse and Arch have the `haproxy.service` state failing
* Amazon fails at `verify` step with one test

**Comment by myii** [comment]
@daks Nice work, I've added this PR to Taiga, as you may have already seen.  I'll probably come back to this at some point after https://github.com/netmanagers/salt-image-builder/pull/38 has been merged, because we've got more images to test with, including `ubuntu-20.04`.

**Comment by myii** [comment]
@daks So I've finally got around to running this through the `ssf-formula`.  I had to start with a commit to modify `.kitchen.yml` => `kitchen.yml`.  The other commit contains both the standardised structure as well as adding the new pre-salted images.

* https://github.com/saltstack-formulas/template-formula/commit/3860bf91bda5cde38b3a4e3d87affd9105a2c0e9
* https://github.com/myii/haproxy-formula/commit/667ba395be99726490f6146ece919145b291b618

The result so far is the same as the one here (only Debian and Ubuntu working):

* https://travis-ci.org/github/myii/haproxy-formula/builds/693322584

Took it further and tested all of the Debian and Ubuntu instances -- all of them are working:

* https://travis-ci.org/github/myii/haproxy-formula/builds/693323886

So could end up using a similar matrix to the `mysql-formula`:

* https://travis-ci.com/github/saltstack-formulas/mysql-formula/builds/168961729

**Comment by myii** [comment]
Merged, with additional commits for standardisation.  Thanks for preparing this, @daks.

**Comment by daks** [comment]
Thanks @myii for finishing the job :)

**Pull request merged**
