### PR TITLE
Add missing require in config.sls

### PR DESCRIPTION
**Pull request by msciciel**
Without require_in service could be started before file generation and fail.

### CODE REVIEW

**Comment by babilen** [comment]
Would be great if you could rebase this branch to get rid of all the merge commits.

**Comment by ChrisLundquist** [comment]
@babilen `git cherry-pick 2a2cf68` should do the trick. 

If msciciel rebases it will be a different commit sha. Then a force push would be required, breaking any other existing branches referencing these commits.

**Comment by gravyboat** [comment]
@ChrisLundquist There are no other PRs which touch this file, a rebase would be fine.

**Comment by ChrisLundquist** [comment]
No other PRs to *this* repo. It looks like msciciel might have his own version on another remote based on the branch name `itg`

I was just trying to offer a way to accept his change (while giving him credit) without waiting.

**Comment by gravyboat** [comment]
Ahh yeah that's fair. If @msciciel doesn't rebase in a couple of days one of us will take care of it or we'll just merge this in. Thanks for the note!

**Comment by msciciel** [comment]
I was unable to do rebase. I'll try again after extending my knowledge. Give me few days.

**Comment by gravyboat** [comment]
@msciciel No worries, thanks for taking a look. If you can't get it working please let us know and myself or @babilen will take care of it.

**Comment by babilen** [comment]
@msciciel The basic idea is that you perform an "interactive rebase" on your local branch and then "force push" it to github again. Interactive rebases are explained in https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History where you want to remove the three "merge" commits and then rebase against master. The latter is detailed in https://git-scm.com/book/en/v2/Git-Branching-Rebasing and essentially boils down to "git pull --rebase" (which you could set as default behaviour in your git config). Once your master branch is in the state you want it to be you can force push it to Github.

I would furthermore suggest to work on feature branches in the future so that your master branch doesn't diverge from upstream's (i.e. salt's) master branch.

Let us know if you have further questions and thanks again!

**Comment by msciciel** [comment]
I've made better PR: https://github.com/saltstack-formulas/haproxy-formula/pull/43. This can be closed.

**Pull request closed without merging**
