### PR TITLE
allow for loops to accept single line entries not only dicts and added functions

### PR DESCRIPTION
**Pull request by bigbosst**
Updated for loops to check for single non-dict string ie:
options:
  - forwardfor
VS 
options: forwardfor

added many options/commands such as sticktables, tcprequests, tcpresponses, stickons, appsessions

### CODE REVIEW

**Comment by nmadhok** [comment]
@bigbosst Rebase

**Comment by bigbosst** [comment]
Rebased with some logic fixes to previous commit

**Comment by gravyboat** [comment]
@bigbosst Sorry to ask one more thing, can you squash real quick?

**Comment by bigbosst** [comment]
no worries, should be good now

**Comment by gravyboat** [comment]
Thanks!

**Pull request merged**
