### PR TITLE
Use k,v in template

### PR DESCRIPTION
**Pull request by morsik**
You had fantasy for using list in `.iteritems()`… :D

Not tested. Changed "on fly" when I looked into template file.

### CODE REVIEW

**Comment by gravyboat** [comment]
Could you please test it? This is a large modification.

**Comment by morsik** [comment]
Fixed one thing, looks like it works now.

**Comment by iggy** [comment]
You might as well replace iteritems with items while you are in there...

**Comment by morsik** [comment]
I wanted to do so, but I didn't want to do it in one Pull Request as they are 2 different changes.
(git rules: atomic commits) Move that talk to #16 ;)

**Comment by morsik** [comment]
Is `|dictsort` is ok? ;)
Should be better than `.items()`/`.iteritems()`, see #16.

**Comment by gravyboat** [comment]
@morsik We now have a conflict of your usage of dictsort and the recently merged https://github.com/saltstack-formulas/haproxy-formula/pull/37 that @abednarik wrote. @abednarik do you have any concerns over using dictsort here? I don't have any, but I also don't use haproxy at all so I'm not sure if the sorting would be problematic for some users.

**Comment by abednarik** [comment]
Ok. Also I don't have any complain regarding dictsort as long as formula works good I'm just fine. We can drop this PR.

**Comment by gravyboat** [comment]
@abednarik Yours was already merged, @morsik needs to rebase, no worries!

**Comment by morsik** [comment]
Oh god…

**Comment by gravyboat** [comment]
@morsik What's wrong? Rebase should detect his updates versus your changes and there should be no issue, just use a merge strategy of yours instead of his.

**Comment by morsik** [comment]
I hate those conflicts... check now, and don't make conflicts when it's not needed next time, please?

**Comment by gravyboat** [comment]
@morsik I also don't like the conflicts but it happens, none of us are paid to work on this stuff as we're all volunteers, sometimes mistakes happen. Thanks for fixing it up.

**Comment by abednarik** [comment]
Sorry for any inconvenience and thanks both.

Cheers

**Comment by morsik** [comment]
Thanks, unfortunaletly GitHub doesn't have option to do Rebase so I had to it manually (and learn how to do it :P)

**Pull request merged**
