### PR TITLE
Added Kitchen tests

### PR DESCRIPTION
**Pull request by daks**
Please consider this pull request which adds code to:
  
- enable TravisCI tests
- adds some basic Kitchen/Inspec tests, at the moment only package, some config in file, and service
- pillar.example is used for tests, but TLS directives have been commented out
- tests dedicated states and pillars are added

Please also consider activating TravisCI on this repository.
Thanks.

### CODE REVIEW

**Comment by javierbertoli** [comment]
So far, it LGTM. Travis seems to be enabled (as this PR has passed the tests you wrote :smile: )

**Comment by daks** [comment]
Yes, in fact, great. Tests pass, but are limited to Debian, and not really advanced, but this job can be completed in a second step.

**Comment by javierbertoli** [comment]
Mind you add a couple simple tests (ie, to see the package is installed and the service is running) so we merge? I think those 2 + the ones you already wrote are a great 1st. step

**Comment by gtmanfred** [comment]
highly recommend testinfra/pytest/docker connector for testing if packages are installed https://testinfra.readthedocs.io/en/latest/

**Comment by daks** [comment]
@javierbertoli package is already verified, and I added service checks

**Comment by javierbertoli** [comment]
Merged. Thanks @daks and @gtmanfred!

**Pull request merged**
